/* Constent Optionts
     - blood Groups in line number 5
     - district options in line number 17
     - upazila options in line number 85
*/

export const bloodGroups = [
    { id: 1, label: "A+", name: "A+" },
    { id: 2, label: "A-", name: "A-" },
    { id: 3, label: "B+", name: "B+" },
    { id: 4, label: "B-", name: "B-" },
    { id: 5, label: "O+", name: "O+" },
    { id: 6, label: "O-", name: "O-" },
    { id: 7, label: "AB+", name: "AB+" },
    { id: 8, label: "AB-", name: "AB-" },
];

export const districtOptions = [
    { id: "1", name: "Comilla" },
    { id: "2", name: "Feni" },
    { id: "3", name: "Brahmanbaria" },
    { id: "4", name: "Rangamati" },
    { id: "5", name: "Noakhali" },
    { id: "6", name: "Chandpur" },
    { id: "7", name: "Lakshmipur" },
    { id: "8", name: "Chattogram" },
    { id: "9", name: "Coxsbazar" },
    { id: "10", name: "Khagrachhari" },
    { id: "11", name: "Bandarban" },
    { id: "12", name: "Sirajganj" },
    { id: "13", name: "Pabna" },
    { id: "14", name: "Bogura" },
    { id: "15", name: "Rajshahi" },
    { id: "16", name: "Natore" },
    { id: "17", name: "Joypurhat" },
    { id: "18", name: "Chapainawabganj" },
    { id: "19", name: "Naogaon" },
    { id: "20", name: "Jashore" },
    { id: "21", name: "Satkhira" },
    { id: "22", name: "Meherpur" },
    { id: "23", name: "Narail" },
    { id: "24", name: "Chuadanga" },
    { id: "25", name: "Kushtia" },
    { id: "26", name: "Magura" },
    { id: "27", name: "Khulna" },
    { id: "28", name: "Bagerhat" },
    { id: "29", name: "Jhenaidah" },
    { id: "30", name: "Jhalakathi" },
    { id: "31", name: "Patuakhali" },
    { id: "32", name: "Pirojpur" },
    { id: "33", name: "Barisal" },
    { id: "34", name: "Bhola" },
    { id: "35", name: "Barguna" },
    { id: "36", name: "Sylhet" },
    { id: "37", name: "Moulvibazar" },
    { id: "38", name: "Habiganj" },
    { id: "39", name: "Sunamganj" },
    { id: "40", name: "Narsingdi" },
    { id: "41", name: "Gazipur" },
    { id: "42", name: "Shariatpur" },
    { id: "43", name: "Narayanganj" },
    { id: "44", name: "Tangail" },
    { id: "45", name: "Kishoreganj" },
    { id: "46", name: "Manikganj" },
    { id: "47", name: "Dhaka" },
    { id: "48", name: "Munshiganj" },
    { id: "49", name: "Rajbari" },
    { id: "50", name: "Madaripur" },
    { id: "51", name: "Gopalganj" },
    { id: "52", name: "Faridpur" },
    { id: "53", name: "Panchagarh" },
    { id: "54", name: "Dinajpur" },
    { id: "55", name: "Lalmonirhat" },
    { id: "56", name: "Nilphamari" },
    { id: "57", name: "Gaibandha" },
    { id: "58", name: "Thakurgaon" },
    { id: "59", name: "Rangpur" },
    { id: "60", name: "Kurigram" },
    { id: "61", name: "Sherpur" },
    { id: "62", name: "Mymensingh" },
    { id: "63", name: "Jamalpur" },
    { id: "64", name: "Netrokona" },
];

export const upzilaOptions = [
    { id: "1", name: "Debidwar", district_id: "1" },
    { id: "2", name: "Barura", district_id: "1" },
    { id: "3", name: "Brahmanpara", district_id: "1" },
    { id: "4", name: "Chandina", district_id: "1" },
    { id: "5", name: "Chauddagram", district_id: "1" },
    { id: "6", name: "Daudkandi", district_id: "1" },
    { id: "7", name: "Homna", district_id: "1" },
    { id: "8", name: "Laksam", district_id: "1" },
    { id: "9", name: "Muradnagar", district_id: "1" },
    { id: "10", name: "Nangalkot", district_id: "1" },
    { id: "11", name: "Comilla Sadar", district_id: "1" },
    { id: "12", name: "Meghna", district_id: "1" },
    { id: "13", name: "Monohargonj", district_id: "1" },
    { id: "14", name: "Sadarsouth", district_id: "1" },
    { id: "15", name: "Titas", district_id: "1" },
    { id: "16", name: "Burichang", district_id: "1" },
    { id: "17", name: "Lalmai", district_id: "1" },
    { id: "18", name: "Chhagalnaiya", district_id: "2" },
    { id: "19", name: "Feni Sadar", district_id: "2" },
    { id: "20", name: "Sonagazi", district_id: "2" },
    { id: "21", name: "Fulgazi", district_id: "2" },
    { id: "22", name: "Parshuram", district_id: "2" },
    { id: "23", name: "Daganbhuiyan", district_id: "2" },
    { id: "24", name: "Brahmanbaria Sadar", district_id: "3" },
    { id: "25", name: "Kasba", district_id: "3" },
    { id: "26", name: "Nasirnagar", district_id: "3" },
    { id: "27", name: "Sarail", district_id: "3" },
    { id: "28", name: "Ashuganj", district_id: "3" },
    { id: "29", name: "Akhaura", district_id: "3" },
    { id: "30", name: "Nabinagar", district_id: "3" },
    { id: "31", name: "Bancharampur", district_id: "3" },
    { id: "32", name: "Bijoynagar", district_id: "3" },
    { id: "33", name: "Rangamati Sadar", district_id: "4" },
    { id: "34", name: "Kaptai", district_id: "4" },
    { id: "35", name: "Kawkhali", district_id: "4" },
    { id: "36", name: "Baghaichari", district_id: "4" },
    { id: "37", name: "Barkal", district_id: "4" },
    { id: "38", name: "Langadu", district_id: "4" },
    { id: "39", name: "Rajasthali", district_id: "4" },
    { id: "40", name: "Belaichari", district_id: "4" },
    { id: "41", name: "Juraichari", district_id: "4" },
    { id: "42", name: "Naniarchar", district_id: "4" },
    { id: "43", name: "Noakhali Sadar", district_id: "5" },
    { id: "44", name: "Companiganj", district_id: "5" },
    { id: "45", name: "Begumganj", district_id: "5" },
    { id: "46", name: "Hatia", district_id: "5" },
    { id: "47", name: "Subarnachar", district_id: "5" },
    { id: "48", name: "Kabirhat", district_id: "5" },
    { id: "49", name: "Senbug", district_id: "5" },
    { id: "50", name: "Chatkhil", district_id: "5" },
    { id: "51", name: "Sonaimori", district_id: "5" },
    { id: "52", name: "Haimchar", district_id: "6" },
    { id: "53", name: "Kachua", district_id: "6" },
    { id: "54", name: "Shahrasti", district_id: "6" },
    { id: "55", name: "Chandpur Sadar", district_id: "6" },
    { id: "56", name: "Matlab South", district_id: "6" },
    { id: "57", name: "Hajiganj", district_id: "6" },
    { id: "58", name: "Matlab North", district_id: "6" },
    { id: "59", name: "Faridgonj", district_id: "6" },
    { id: "60", name: "Lakshmipur Sadar", district_id: "7" },
    { id: "61", name: "Kamalnagar", district_id: "7" },
    { id: "62", name: "Raipur", district_id: "7" },
    { id: "63", name: "Ramgati", district_id: "7" },
    { id: "64", name: "Ramganj", district_id: "7" },
    { id: "65", name: "Rangunia", district_id: "8" },
    { id: "66", name: "Sitakunda", district_id: "8" },
    { id: "67", name: "Mirsharai", district_id: "8" },
    { id: "68", name: "Patiya", district_id: "8" },
    { id: "69", name: "Sandwip", district_id: "8" },
    { id: "70", name: "Banshkhali", district_id: "8" },
    { id: "71", name: "Boalkhali", district_id: "8" },
    { id: "72", name: "Anwara", district_id: "8" },
    { id: "73", name: "Chandanaish", district_id: "8" },
    { id: "74", name: "Satkania", district_id: "8" },
    { id: "75", name: "Lohagara", district_id: "8" },
    { id: "76", name: "Hathazari", district_id: "8" },
    { id: "77", name: "Fatikchhari", district_id: "8" },
    { id: "78", name: "Raozan", district_id: "8" },
    { id: "79", name: "Karnafuli", district_id: "8" },
    { id: "80", name: "Coxsbazar Sadar", district_id: "9" },
    { id: "81", name: "Chakaria", district_id: "9" },
    { id: "82", name: "Kutubdia", district_id: "9" },
    { id: "83", name: "Ukhiya", district_id: "9" },
    { id: "84", name: "Moheshkhali", district_id: "9" },
    { id: "85", name: "Pekua", district_id: "9" },
    { id: "86", name: "Ramu", district_id: "9" },
    { id: "87", name: "Teknaf", district_id: "9" },
    { id: "88", name: "Khagrachhari Sadar", district_id: "10" },
    { id: "89", name: "Dighinala", district_id: "10" },
    { id: "90", name: "Panchari", district_id: "10" },
    { id: "91", name: "Laxmichhari", district_id: "10" },
    { id: "92", name: "Mohalchari", district_id: "10" },
    { id: "93", name: "Manikchari", district_id: "10" },
    { id: "94", name: "Ramgarh", district_id: "10" },
    { id: "95", name: "Matiranga", district_id: "10" },
    { id: "96", name: "Guimara", district_id: "10" },
    { id: "97", name: "Bandarban Sadar", district_id: "11" },
    { id: "98", name: "Alikadam", district_id: "11" },
    { id: "99", name: "Naikhongchhari", district_id: "11" },
    { id: "100", name: "Rowangchhari", district_id: "11" },
    { id: "101", name: "Lama", district_id: "11" },
    { id: "102", name: "Ruma", district_id: "11" },
    { id: "103", name: "Thanchi", district_id: "11" },
    { id: "104", name: "Belkuchi", district_id: "12" },
    { id: "105", name: "Chauhali", district_id: "12" },
    { id: "106", name: "Kamarkhand", district_id: "12" },
    { id: "107", name: "Kazipur", district_id: "12" },
    { id: "108", name: "Raigonj", district_id: "12" },
    { id: "109", name: "Shahjadpur", district_id: "12" },
    { id: "110", name: "Sirajganj Sadar", district_id: "12" },
    { id: "111", name: "Tarash", district_id: "12" },
    { id: "112", name: "Ullapara", district_id: "12" },
    { id: "113", name: "Sujanagar", district_id: "13" },
    { id: "114", name: "Ishurdi", district_id: "13" },
    { id: "115", name: "Bhangura", district_id: "13" },
    { id: "116", name: "Pabna Sadar", district_id: "13" },
    { id: "117", name: "Bera", district_id: "13" },
    { id: "118", name: "Atghoria", district_id: "13" },
    { id: "119", name: "Chatmohar", district_id: "13" },
    { id: "120", name: "Santhia", district_id: "13" },
    { id: "121", name: "Faridpur", district_id: "13" },
    { id: "122", name: "Kahaloo", district_id: "14" },
    { id: "123", name: "Bogra Sadar", district_id: "14" },
    { id: "124", name: "Shariakandi", district_id: "14" },
    { id: "125", name: "Shajahanpur", district_id: "14" },
    { id: "126", name: "Dupchanchia", district_id: "14" },
    { id: "127", name: "Adamdighi", district_id: "14" },
    { id: "128", name: "Nondigram", district_id: "14" },
    { id: "129", name: "Sonatala", district_id: "14" },
    { id: "130", name: "Dhunot", district_id: "14" },
    { id: "131", name: "Gabtali", district_id: "14" },
    { id: "132", name: "Sherpur", district_id: "14" },
    { id: "133", name: "Shibganj", district_id: "14" },
    { id: "134", name: "Paba", district_id: "15" },
    { id: "135", name: "Durgapur", district_id: "15" },
    { id: "136", name: "Mohonpur", district_id: "15" },
    { id: "137", name: "Charghat", district_id: "15" },
    { id: "138", name: "Puthia", district_id: "15" },
    { id: "139", name: "Bagha", district_id: "15" },
    { id: "140", name: "Godagari", district_id: "15" },
    { id: "141", name: "Tanore", district_id: "15" },
    { id: "142", name: "Bagmara", district_id: "15" },
    { id: "143", name: "Natore Sadar", district_id: "16" },
    { id: "144", name: "Singra", district_id: "16" },
    { id: "145", name: "Baraigram", district_id: "16" },
    { id: "146", name: "Bagatipara", district_id: "16" },
    { id: "147", name: "Lalpur", district_id: "16" },
    { id: "148", name: "Gurudaspur", district_id: "16" },
    { id: "149", name: "Naldanga", district_id: "16" },
    { id: "150", name: "Akkelpur", district_id: "17" },
    { id: "151", name: "Kalai", district_id: "17" },
    { id: "152", name: "Khetlal", district_id: "17" },
    { id: "153", name: "Panchbibi", district_id: "17" },
    { id: "154", name: "Joypurhat Sadar", district_id: "17" },
    { id: "155", name: "Chapainawabganj Sadar", district_id: "18" },
    { id: "156", name: "Gomostapur", district_id: "18" },
    { id: "157", name: "Nachol", district_id: "18" },
    { id: "158", name: "Bholahat", district_id: "18" },
    { id: "159", name: "Shibganj", district_id: "18" },
    { id: "160", name: "Mohadevpur", district_id: "19" },
    { id: "161", name: "Badalgachi", district_id: "19" },
    { id: "162", name: "Patnitala", district_id: "19" },
    { id: "163", name: "Dhamoirhat", district_id: "19" },
    { id: "164", name: "Niamatpur", district_id: "19" },
    { id: "165", name: "Manda", district_id: "19" },
    { id: "166", name: "Atrai", district_id: "19" },
    { id: "167", name: "Raninagar", district_id: "19" },
    { id: "168", name: "Naogaon Sadar", district_id: "19" },
    { id: "169", name: "Porsha", district_id: "19" },
    { id: "170", name: "Sapahar", district_id: "19" },
    { id: "171", name: "Manirampur", district_id: "20" },
    { id: "172", name: "Abhaynagar", district_id: "20" },
    { id: "173", name: "Bagherpara", district_id: "20" },
    { id: "174", name: "Chougachha", district_id: "20" },
    { id: "175", name: "Jhikargacha", district_id: "20" },
    { id: "176", name: "Keshabpur", district_id: "20" },
    { id: "177", name: "Jessore Sadar", district_id: "20" },
    { id: "178", name: "Sharsha", district_id: "20" },
    { id: "179", name: "Assasuni", district_id: "21" },
    { id: "180", name: "Debhata", district_id: "21" },
    { id: "181", name: "Kalaroa", district_id: "21" },
    { id: "182", name: "Satkhira Sadar", district_id: "21" },
    { id: "183", name: "Shyamnagar", district_id: "21" },
    { id: "184", name: "Tala", district_id: "21" },
    { id: "185", name: "Kaliganj", district_id: "21" },
    { id: "186", name: "Mujibnagar", district_id: "22" },
    { id: "187", name: "Meherpur Sadar", district_id: "22" },
    { id: "188", name: "Gangni", district_id: "22" },
    { id: "189", name: "Narail Sadar", district_id: "23" },
    { id: "190", name: "Lohagara", district_id: "23" },
    { id: "191", name: "Kalia", district_id: "23" },
    { id: "192", name: "Chuadanga Sadar", district_id: "24" },
    { id: "193", name: "Alamdanga", district_id: "24" },
    { id: "194", name: "Damurhuda", district_id: "24" },
    { id: "195", name: "Jibannagar", district_id: "24" },
    { id: "196", name: "Kushtia Sadar", district_id: "25" },
    { id: "197", name: "Kumarkhali", district_id: "25" },
    { id: "198", name: "Khoksa", district_id: "25" },
    { id: "199", name: "Mirpur", district_id: "25" },
    { id: "200", name: "Daulatpur", district_id: "25" },
    { id: "201", name: "Bheramara", district_id: "25" },
    { id: "202", name: "Shalikha", district_id: "26" },
    { id: "203", name: "Sreepur", district_id: "26" },
    { id: "204", name: "Magura Sadar", district_id: "26" },
    { id: "205", name: "Mohammadpur", district_id: "26" },
    { id: "206", name: "Paikgasa", district_id: "27" },
    { id: "207", name: "Fultola", district_id: "27" },
    { id: "208", name: "Digholia", district_id: "27" },
    { id: "209", name: "Rupsha", district_id: "27" },
    { id: "210", name: "Terokhada", district_id: "27" },
    { id: "211", name: "Dumuria", district_id: "27" },
    { id: "212", name: "Botiaghata", district_id: "27" },
    { id: "213", name: "Dakop", district_id: "27" },
    { id: "214", name: "Koyra", district_id: "27" },
    { id: "215", name: "Fakirhat", district_id: "28" },
    { id: "216", name: "Bagerhat Sadar", district_id: "28" },
    { id: "217", name: "Mollahat", district_id: "28" },
    { id: "218", name: "Sarankhola", district_id: "28" },
    { id: "219", name: "Rampal", district_id: "28" },
    { id: "220", name: "Morrelganj", district_id: "28" },
    { id: "221", name: "Kachua", district_id: "28" },
    { id: "222", name: "Mongla", district_id: "28" },
    { id: "223", name: "Chitalmari", district_id: "28" },
    { id: "224", name: "Jhenaidah Sadar", district_id: "29" },
    { id: "225", name: "Shailkupa", district_id: "29" },
    { id: "226", name: "Harinakundu", district_id: "29" },
    { id: "227", name: "Kaliganj", district_id: "29" },
    { id: "228", name: "Kotchandpur", district_id: "29" },
    { id: "229", name: "Moheshpur", district_id: "29" },
    { id: "230", name: "Jhalakathi Sadar", district_id: "30" },
    { id: "231", name: "Kathalia", district_id: "30" },
    { id: "232", name: "Nalchity", district_id: "30" },
    { id: "233", name: "Rajapur", district_id: "30" },
    { id: "234", name: "Bauphal", district_id: "31" },
    { id: "235", name: "Patuakhali Sadar", district_id: "31" },
    { id: "236", name: "Dumki", district_id: "31" },
    { id: "237", name: "Dashmina", district_id: "31" },
    { id: "238", name: "Kalapara", district_id: "31" },
    { id: "239", name: "Mirzaganj", district_id: "31" },
    { id: "240", name: "Galachipa", district_id: "31" },
    { id: "241", name: "Rangabali", district_id: "31" },
    { id: "242", name: "Pirojpur Sadar", district_id: "32" },
    { id: "243", name: "Nazirpur", district_id: "32" },
    { id: "244", name: "Kawkhali", district_id: "32" },
    { id: "245", name: "Zianagar", district_id: "32" },
    { id: "246", name: "Bhandaria", district_id: "32" },
    { id: "247", name: "Mathbaria", district_id: "32" },
    { id: "248", name: "Nesarabad", district_id: "32" },
    { id: "249", name: "Barisal Sadar", district_id: "33" },
    { id: "250", name: "Bakerganj", district_id: "33" },
    { id: "251", name: "Babuganj", district_id: "33" },
    { id: "252", name: "Wazirpur", district_id: "33" },
    { id: "253", name: "Banaripara", district_id: "33" },
    { id: "254", name: "Gournadi", district_id: "33" },
    { id: "255", name: "Agailjhara", district_id: "33" },
    { id: "256", name: "Mehendiganj", district_id: "33" },
    { id: "257", name: "Muladi", district_id: "33" },
    { id: "258", name: "Hizla", district_id: "33" },
    { id: "259", name: "Bhola Sadar", district_id: "34" },
    { id: "260", name: "Borhan Sddin", district_id: "34" },
    { id: "261", name: "Charfesson", district_id: "34" },
    { id: "262", name: "Doulatkhan", district_id: "34" },
    { id: "263", name: "Monpura", district_id: "34" },
    { id: "264", name: "Tazumuddin", district_id: "34" },
    { id: "265", name: "Lalmohan", district_id: "34" },
    { id: "266", name: "Amtali", district_id: "35" },
    { id: "267", name: "Barguna Sadar", district_id: "35" },
    { id: "268", name: "Betagi", district_id: "35" },
    { id: "269", name: "Bamna", district_id: "35" },
    { id: "270", name: "Pathorghata", district_id: "35" },
    { id: "271", name: "Taltali", district_id: "35" },
    { id: "272", name: "Balaganj", district_id: "36" },
    { id: "273", name: "Beanibazar", district_id: "36" },
    { id: "274", name: "Bishwanath", district_id: "36" },
    { id: "275", name: "Companiganj", district_id: "36" },
    { id: "276", name: "Fenchuganj", district_id: "36" },
    { id: "277", name: "Golapganj", district_id: "36" },
    { id: "278", name: "Gowainghat", district_id: "36" },
    { id: "279", name: "Jaintiapur", district_id: "36" },
    { id: "280", name: "Kanaighat", district_id: "36" },
    { id: "281", name: "Sylhet Sadar", district_id: "36" },
    { id: "282", name: "Zakiganj", district_id: "36" },
    { id: "283", name: "Dakshinsurma", district_id: "36" },
    { id: "284", name: "Osmaninagar", district_id: "36" },
    { id: "285", name: "Barlekha", district_id: "37" },
    { id: "286", name: "Kamolganj", district_id: "37" },
    { id: "287", name: "Kulaura", district_id: "37" },
    { id: "288", name: "Moulvibazar Sadar", district_id: "37" },
    { id: "289", name: "Rajnagar", district_id: "37" },
    { id: "290", name: "Sreemangal", district_id: "37" },
    { id: "291", name: "Juri", district_id: "37" },
    { id: "292", name: "Nabiganj", district_id: "38" },
    { id: "293", name: "Bahubal", district_id: "38" },
    { id: "294", name: "Ajmiriganj", district_id: "38" },
    { id: "295", name: "Baniachong", district_id: "38" },
    { id: "296", name: "Lakhai", district_id: "38" },
    { id: "297", name: "Chunarughat", district_id: "38" },
    { id: "298", name: "Habiganj Sadar", district_id: "38" },
    { id: "299", name: "Madhabpur", district_id: "38" },
    { id: "300", name: "Sunamganj Sadar", district_id: "39" },
    { id: "301", name: "South Sunamganj", district_id: "39" },
    { id: "302", name: "Bishwambarpur", district_id: "39" },
    { id: "303", name: "Chhatak", district_id: "39" },
    { id: "304", name: "Jagannathpur", district_id: "39" },
    { id: "305", name: "Dowarabazar", district_id: "39" },
    { id: "306", name: "Tahirpur", district_id: "39" },
    { id: "307", name: "Dharmapasha", district_id: "39" },
    { id: "308", name: "Jamalganj", district_id: "39" },
    { id: "309", name: "Shalla", district_id: "39" },
    { id: "310", name: "Derai", district_id: "39" },
    { id: "311", name: "Belabo", district_id: "40" },
    { id: "312", name: "Monohardi", district_id: "40" },
    { id: "313", name: "Narsingdi Sadar", district_id: "40" },
    { id: "314", name: "Palash", district_id: "40" },
    { id: "315", name: "Raipura", district_id: "40" },
    { id: "316", name: "Shibpur", district_id: "40" },
    { id: "317", name: "Kaliganj", district_id: "41" },
    { id: "318", name: "Kaliakair", district_id: "41" },
    { id: "319", name: "Kapasia", district_id: "41" },
    { id: "320", name: "Gazipur Sadar", district_id: "41" },
    { id: "321", name: "Sreepur", district_id: "41" },
    { id: "322", name: "Shariatpur Sadar", district_id: "42" },
    { id: "323", name: "Naria", district_id: "42" },
    { id: "324", name: "Zajira", district_id: "42" },
    { id: "325", name: "Gosairhat", district_id: "42" },
    { id: "326", name: "Bhedarganj", district_id: "42" },
    { id: "327", name: "Damudya", district_id: "42" },
    { id: "328", name: "Araihazar", district_id: "43" },
    { id: "329", name: "Bandar", district_id: "43" },
    { id: "330", name: "Narayanganj Sadar", district_id: "43" },
    { id: "331", name: "Rupganj", district_id: "43" },
    { id: "332", name: "Sonargaon", district_id: "43" },
    { id: "333", name: "Basail", district_id: "44" },
    { id: "334", name: "Bhuapur", district_id: "44" },
    { id: "335", name: "Delduar", district_id: "44" },
    { id: "336", name: "Ghatail", district_id: "44" },
    { id: "337", name: "Gopalpur", district_id: "44" },
    { id: "338", name: "Madhupur", district_id: "44" },
    { id: "339", name: "Mirzapur", district_id: "44" },
    { id: "340", name: "Nagarpur", district_id: "44" },
    { id: "341", name: "Sakhipur", district_id: "44" },
    { id: "342", name: "Tangail Sadar", district_id: "44" },
    { id: "343", name: "Kalihati", district_id: "44" },
    { id: "344", name: "Dhanbari", district_id: "44" },
    { id: "345", name: "Itna", district_id: "45" },
    { id: "346", name: "Katiadi", district_id: "45" },
    { id: "347", name: "Bhairab", district_id: "45" },
    { id: "348", name: "Tarail", district_id: "45" },
    { id: "349", name: "Hossainpur", district_id: "45" },
    { id: "350", name: "Pakundia", district_id: "45" },
    { id: "351", name: "Kuliarchar", district_id: "45" },
    { id: "352", name: "Kishoreganj Sadar", district_id: "45" },
    { id: "353", name: "Karimgonj", district_id: "45" },
    { id: "354", name: "Bajitpur", district_id: "45" },
    { id: "355", name: "Austagram", district_id: "45" },
    { id: "356", name: "Mithamoin", district_id: "45" },
    { id: "357", name: "Nikli", district_id: "45" },
    { id: "358", name: "Harirampur", district_id: "46" },
    { id: "359", name: "Saturia", district_id: "46" },
    { id: "360", name: "Manikganj Sadar", district_id: "46" },
    { id: "361", name: "Gior", district_id: "46" },
    { id: "362", name: "Shibaloy", district_id: "46" },
    { id: "363", name: "Doulatpur", district_id: "46" },
    { id: "364", name: "Singiar", district_id: "46" },
    { id: "365", name: "Savar", district_id: "47" },
    { id: "366", name: "Dhamrai", district_id: "47" },
    { id: "367", name: "Keraniganj", district_id: "47" },
    { id: "368", name: "Nawabganj", district_id: "47" },
    { id: "369", name: "Dohar", district_id: "47" },
    { id: "370", name: "Munshiganj Sadar", district_id: "48" },
    { id: "371", name: "Sreenagar", district_id: "48" },
    { id: "372", name: "Sirajdikhan", district_id: "48" },
    { id: "373", name: "Louhajanj", district_id: "48" },
    { id: "374", name: "Gajaria", district_id: "48" },
    { id: "375", name: "Tongibari", district_id: "48" },
    { id: "376", name: "Rajbari Sadar", district_id: "49" },
    { id: "377", name: "Goalanda", district_id: "49" },
    { id: "378", name: "Pangsa", district_id: "49" },
    { id: "379", name: "Baliakandi", district_id: "49" },
    { id: "380", name: "Kalukhali", district_id: "49" },
    { id: "381", name: "Madaripur Sadar", district_id: "50" },
    { id: "382", name: "Shibchar", district_id: "50" },
    { id: "383", name: "Kalkini", district_id: "50" },
    { id: "384", name: "Rajoir", district_id: "50" },
    { id: "385", name: "Gopalganj Sadar", district_id: "51" },
    { id: "386", name: "Kashiani", district_id: "51" },
    { id: "387", name: "Tungipara", district_id: "51" },
    { id: "388", name: "Kotalipara", district_id: "51" },
    { id: "389", name: "Muksudpur", district_id: "51" },
    { id: "390", name: "Faridpur Sadar", district_id: "52" },
    { id: "391", name: "Alfadanga", district_id: "52" },
    { id: "392", name: "Boalmari", district_id: "52" },
    { id: "393", name: "Sadarpur", district_id: "52" },
    { id: "394", name: "Nagarkanda", district_id: "52" },
    { id: "395", name: "Bhanga", district_id: "52" },
    { id: "396", name: "Charbhadrasan", district_id: "52" },
    { id: "397", name: "Madhukhali", district_id: "52" },
    { id: "398", name: "Saltha", district_id: "52" },
    { id: "399", name: "Panchagarh Sadar", district_id: "53" },
    { id: "400", name: "Debiganj", district_id: "53" },
    { id: "401", name: "Boda", district_id: "53" },
    { id: "402", name: "Atwari", district_id: "53" },
    { id: "403", name: "Tetulia", district_id: "53" },
    { id: "404", name: "Nawabganj", district_id: "54" },
    { id: "405", name: "Birganj", district_id: "54" },
    { id: "406", name: "Ghoraghat", district_id: "54" },
    { id: "407", name: "Birampur", district_id: "54" },
    { id: "408", name: "Parbatipur", district_id: "54" },
    { id: "409", name: "Bochaganj", district_id: "54" },
    { id: "410", name: "Kaharol", district_id: "54" },
    { id: "411", name: "Fulbari", district_id: "54" },
    { id: "412", name: "Dinajpur Sadar", district_id: "54" },
    { id: "413", name: "Hakimpur", district_id: "54" },
    { id: "414", name: "Khansama", district_id: "54" },
    { id: "415", name: "Birol", district_id: "54" },
    { id: "416", name: "Chirirbandar", district_id: "54" },
    { id: "417", name: "Lalmonirhat Sadar", district_id: "55" },
    { id: "418", name: "Kaliganj", district_id: "55" },
    { id: "419", name: "Hatibandha", district_id: "55" },
    { id: "420", name: "Patgram", district_id: "55" },
    { id: "421", name: "Aditmari", district_id: "55" },
    { id: "422", name: "Syedpur", district_id: "56" },
    { id: "423", name: "Domar", district_id: "56" },
    { id: "424", name: "Dimla", district_id: "56" },
    { id: "425", name: "Jaldhaka", district_id: "56" },
    { id: "426", name: "Kishorganj", district_id: "56" },
    { id: "427", name: "Nilphamari Sadar", district_id: "56" },
    { id: "428", name: "Sadullapur", district_id: "57" },
    { id: "429", name: "Gaibandha Sadar", district_id: "57" },
    { id: "430", name: "Palashbari", district_id: "57" },
    { id: "431", name: "Saghata", district_id: "57" },
    { id: "432", name: "Gobindaganj", district_id: "57" },
    { id: "433", name: "Sundarganj", district_id: "57" },
    { id: "434", name: "Phulchari", district_id: "57" },
    { id: "435", name: "Thakurgaon Sadar", district_id: "58" },
    { id: "436", name: "Pirganj", district_id: "58" },
    { id: "437", name: "Ranisankail", district_id: "58" },
    { id: "438", name: "Haripur", district_id: "58" },
    { id: "439", name: "Baliadangi", district_id: "58" },
    { id: "440", name: "Rangpur Sadar", district_id: "59" },
    { id: "441", name: "Gangachara", district_id: "59" },
    { id: "442", name: "Taragonj", district_id: "59" },
    { id: "443", name: "Badargonj", district_id: "59" },
    { id: "444", name: "Mithapukur", district_id: "59" },
    { id: "445", name: "Pirgonj", district_id: "59" },
    { id: "446", name: "Kaunia", district_id: "59" },
    { id: "447", name: "Pirgacha", district_id: "59" },
    { id: "448", name: "Kurigram Sadar", district_id: "60" },
    { id: "449", name: "Nageshwari", district_id: "60" },
    { id: "450", name: "Bhurungamari", district_id: "60" },
    { id: "451", name: "Phulbari", district_id: "60" },
    { id: "452", name: "Rajarhat", district_id: "60" },
    { id: "453", name: "Ulipur", district_id: "60" },
    { id: "454", name: "Chilmari", district_id: "60" },
    { id: "455", name: "Rowmari", district_id: "60" },
    { id: "456", name: "Charrajibpur", district_id: "60" },
    { id: "457", name: "Sherpur Sadar", district_id: "61" },
    { id: "458", name: "Nalitabari", district_id: "61" },
    { id: "459", name: "Sreebordi", district_id: "61" },
    { id: "460", name: "Nokla", district_id: "61" },
    { id: "461", name: "Jhenaigati", district_id: "61" },
    { id: "462", name: "Fulbaria", district_id: "62" },
    { id: "463", name: "Trishal", district_id: "62" },
    { id: "464", name: "Bhaluka", district_id: "62" },
    { id: "465", name: "Muktagacha", district_id: "62" },
    { id: "466", name: "Mymensingh Sadar", district_id: "62" },
    { id: "467", name: "Dhobaura", district_id: "62" },
    { id: "468", name: "Phulpur", district_id: "62" },
    { id: "469", name: "Haluaghat", district_id: "62" },
    { id: "470", name: "Gouripur", district_id: "62" },
    { id: "471", name: "Gafargaon", district_id: "62" },
    { id: "472", name: "Iswarganj", district_id: "62" },
    { id: "473", name: "Nandail", district_id: "62" },
    { id: "474", name: "Tarakanda", district_id: "62" },
    { id: "475", name: "Jamalpur Sadar", district_id: "63" },
    { id: "476", name: "Melandah", district_id: "63" },
    { id: "477", name: "Islampur", district_id: "63" },
    { id: "478", name: "Dewangonj", district_id: "63" },
    { id: "479", name: "Sarishabari", district_id: "63" },
    { id: "480", name: "Madarganj", district_id: "63" },
    { id: "481", name: "Bokshiganj", district_id: "63" },
    { id: "482", name: "Barhatta", district_id: "64" },
    { id: "483", name: "Durgapur", district_id: "64" },
    { id: "484", name: "Kendua", district_id: "64" },
    { id: "485", name: "Atpara", district_id: "64" },
    { id: "486", name: "Madan", district_id: "64" },
    { id: "487", name: "Khaliajuri", district_id: "64" },
    { id: "488", name: "Kalmakanda", district_id: "64" },
    { id: "489", name: "Mohongonj", district_id: "64" },
    { id: "490", name: "Purbadhala", district_id: "64" },
    { id: "491", name: "Netrokona Sadar", district_id: "64" },
    { id: "492", name: "Eidgaon", district_id: "9" },
    { id: "493", name: "Madhyanagar", district_id: "39" },
    { id: "494", name: "Dasar", district_id: "50" },
];
